version: '3'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - 8000:8080
    volumes:
      - ./docs/index.yml:/usr/share/nginx/html/index.yml
    environment:
      API_URL: index.yml
  swagger-watch:
    build: ./swagger-watch
    volumes:
      - ./swagger-watch:/app
      - /app/node_modules
      - ./src:/src
      - ./docs/index.yml:/docs/index.yml
    working_dir: /app
    command: 'node index.js'
